production:
  :concurrency: 20
staging:
  :concurrency: 15
:verbose: false
:concurrency: 10
:pidfile: /channeldispatch/shared/tmp/pids/sidekiq.pid
:queues:
- [critical, 2]
- default
- low
production:
:concurrency: 25
staging:
:concurrency: 15
# :schedule:
#   get_eBay_orders_from_API:
#     cron: '0 */5 * * * *'
#     class: CreateChannelOrderResponseJob